version: 1.0
jobs:
  build:
    docker:
      - image: node:20
    steps:
      - checkout
      - run: npm install
      - run: npm test

  deploy:
    steps:
      - run: echo 'Deploying to production...'
      - run: npm run deploy